language: python

python:
    - "2.7"
    - "3.4"

services:
    - redis-server

install:
    - pip install -r requirements.txt
    - pip install -e .

script:
    - nosetests

notifications:
    email: false
