language: python

python:
    - "2.7"
    - "3.3"

services:
    - redis-server

install:
    - pip install -r dev-requirements.txt
    - pip install -e .

script:
    - nosetests
    - pep8 flask_goat.py
    - pyflakes .

notifications:
    email: false
